# mkdocs.yml
site_name: BoxMOT
theme:
  name: material
  # turn on both section grouping and global expand
  features:
    - navigation.sections
    - navigation.expand

markdown_extensions:
    - mkdocs-click
    - md_in_html

plugins:
  - search
  - include-markdown
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys; sys.path.insert(0, ".")
          options:
            selection:
              members: "__all__"
              filters:
                - "!^update$"

nav:
  - Home: PROJECT_README.md

  - CLI:
    - Track:          modes/track.md
    - Evaluate:       modes/eval.md
    - Tune:           modes/tune.md

  - Trackers:
      - ByteTrack:    trackers/bytetrack.md
      - BotSort:      trackers/botsort.md
      - StrongSort:   trackers/strongsort.md
      - OcSort:       trackers/ocsort.md
      - DeepOcSort:   trackers/deepocsort.md
      # - HybridSort:   api/trackers/hybridsort.md
      - BoostTrack:   trackers/boosttrack.md

