ecc: false
ema_alpha: 0.8979312595206661
iou_thresh: 0.18179688837403396
max_age: 140.0
max_dist: 0.2586684759258714
max_iou_dist: 0.7556200524922695
mc_lambda: 0.9086258006704525
n_init: 1.1420721163957739
nn_budget: 100
