# https://huggingface.co/datasets/noahcao/dancetrack/tree/main
download:
  runs_url: null
  dataset_url: "https://github.com/mikel-brostrom/boxmot/releases/download/v13.0.9/dancetrack-ablation.zip"

benchmark:
  source: "boxmot/engine/trackeval/dancetrack-ablation"
  name: "dancetrack-ablation"
  split: "train"
  classes: "person"
