# https://motchallenge.net/data/MOT20/
download:
  dataset_url: "https://github.com/mikel-brostrom/boxmot/releases/download/v13.0.9/MOT20-ablation.zip"
  dataset_dest: "boxmot/engine/trackeval/MOT20-ablation.zip"

benchmark:
  name: "MOT20-ablation"
  split: "train"
