# https://motchallenge.net/data/MOT20/
download:
  runs_url: "https://github.com/mikel-brostrom/boxmot/releases/download/v12.0.7/runs.zip"
  dataset_url: "https://github.com/mikel-brostrom/boxmot/releases/download/v13.0.9/MOT20-ablation.zip"

benchmark:
  source: "boxmot/engine/trackeval/MOT20-ablation"
  split: "train"
  classes: "person"
