# https://github.com/SportsMOT/SportsMOT
download:
  runs_url: ""
  dataset_url: "https://github.com/mikel-brostrom/boxmot/releases/download/v13.0.9/SportsMOT.zip"

benchmark:
  name: "SportsMOT"
  split: "train"
  classes: "person"
