# https://github.com/SportsMOT/SportsMOT
download:
  runs_url: ""
  dataset_url: "https://github.com/mikel-brostrom/boxmot/releases/download/v13.0.9/SportsMOT.zip"

benchmark:
  source: "boxmot/engine/trackeval/SportsMOT"
  split: "val"
  classes: "person"
