# https://github.com/VisDrone/VisDrone-Dataset
download:
  runs_url: ""
  dataset_url: "https://github.com/mikel-brostrom/boxmot/releases/download/v13.0.9/vizdrone-ablation.zip"

benchmark:
  name: "vizdrone-ablation"
  split: "train"
  classes: "person car truck bus van"
